// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUhj3Zm77ABcQs8Pw8dmQZUc8nZQm_SEA',
    appId: '1:331046206824:web:761fa5e299ad602aa4aadd',
    messagingSenderId: '331046206824',
    projectId: 'institute-mobile-15782',
    authDomain: 'institute-mobile-15782.firebaseapp.com',
    storageBucket: 'institute-mobile-15782.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC09AfDi6ITwitwiOMxhz_xoMiQshrlvp8',
    appId: '1:331046206824:android:fbd6c0a63f8849baa4aadd',
    messagingSenderId: '331046206824',
    projectId: 'institute-mobile-15782',
    storageBucket: 'institute-mobile-15782.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJxddtZswuFht69JD8g7wa2y0pRNd7G2c',
    appId: '1:331046206824:ios:2354bf20038cdf6da4aadd',
    messagingSenderId: '331046206824',
    projectId: 'institute-mobile-15782',
    storageBucket: 'institute-mobile-15782.appspot.com',
    iosClientId: '331046206824-odkln52igmjk9bqs7m6adi6cdp26qevq.apps.googleusercontent.com',
    iosBundleId: 'com.example.instituteManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJxddtZswuFht69JD8g7wa2y0pRNd7G2c',
    appId: '1:331046206824:ios:2354bf20038cdf6da4aadd',
    messagingSenderId: '331046206824',
    projectId: 'institute-mobile-15782',
    storageBucket: 'institute-mobile-15782.appspot.com',
    iosClientId: '331046206824-odkln52igmjk9bqs7m6adi6cdp26qevq.apps.googleusercontent.com',
    iosBundleId: 'com.example.instituteManagementApp',
  );
}
